<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="..\NETReactorSlayerCommon.props" />

	<PropertyGroup>
		<Platform>x86</Platform>
		<OutputPath>..\bin\$(Configuration)\</OutputPath>
		<OutputType>Exe</OutputType>
		<TargetFrameworks>net9.0;net7.0;net48</TargetFrameworks>
		<PlatformTarget>x64</PlatformTarget>

	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net7.0|AnyCPU'">
	  <Prefer32Bit>False</Prefer32Bit>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net7.0|AnyCPU'">
	  <Prefer32Bit>False</Prefer32Bit>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net48|AnyCPU'">
	  <Prefer32Bit>False</Prefer32Bit>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net48|AnyCPU'">
	  <Prefer32Bit>False</Prefer32Bit>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\NETReactorSlayer.Core\NETReactorSlayer.Core.csproj" />
	</ItemGroup>

</Project>
