<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="..\NETReactorSlayerCommon.props" />

	<PropertyGroup>
		<Platform>x86</Platform>
		<OutputPath>..\bin\$(Configuration)\</OutputPath>
		<OutputType>Exe</OutputType>
		<TargetFrameworks>net9.0;net6.0;net7.0;net48;netcoreapp3.1</TargetFrameworks>
		<PlatformTarget>x86</PlatformTarget>

	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net9.0|AnyCPU'">
	  <WarningLevel>8</WarningLevel>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net9.0|AnyCPU'">
	  <WarningLevel>8</WarningLevel>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\NETReactorSlayer.Core\NETReactorSlayer.Core.csproj" />
	</ItemGroup>

</Project>